
mission_name_params:
  prefix: "/RRL_2015_PANDORA_"
  extention: ".tiff"
  color: "DARK_BLUE_F"
  width: 2

checker_params:
  light_color: "LIGHT_GREY"
  dark_color: "DARK_GREY"

scale_params:
  color: "DARK_BLUE_M"
  width: 2

orientation_params:
  color: "DARK_BLUE_M"
  width: 2

