
team:
    name: "Pandora"
    country: "Greece"

robot:
    name: "Gio"
    mode: "A"

csv:
    prefix: "RC2015"
    suffix: "_qr.csv"
    directoryToSave: "/"

services:
    objects: "/data_fusion/get_geotiff"
    csv: "qr_csv/createCSV"
